# Generated by Django 3.2.8 on 2021-11-08 16:38

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LegacySite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encryptedcard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', django_cryptography.fields.encrypt(models.BinaryField(unique=True))),
                ('amount', django_cryptography.fields.encrypt(models.IntegerField())),
                ('fp', django_cryptography.fields.encrypt(models.CharField(max_length=100, unique=True))),
                ('used', models.BooleanField(default=False)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LegacySite.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegacySite.user')),
            ],
        ),
    ]
