name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r /GiftcardSite/Part 1/requirements.txt
    - name: Run Tests
      run: |
        python3 manage.py test egacySite.tests.testattack1#changed per django documentation
